### ISSUE TITLE
🪲[Bug]: Missing Administrative templates

### ISSUE THREAD

**Issue by kennethvs** [srozemuller/IntuneAssistant#118]
### Contact Details

kenneth@itgration.nl

### What happened?

No Administrative Templates shown in both IntuneCLI and IntuneAssistant

### Version

1.0.9

### Steps to reproduce?

This is what i did.

**Comment by srozemuller** [comment]
Administrative templates are in the background categorised as group policy configurations. Changed the name into administrative templates
