### ISSUE TITLE
🪲[Bug]: filter for EntraID groups is not working

### ISSUE THREAD

**Issue by slaet** [srozemuller/IntuneAssistant#131]
### Contact Details

mirko@colemberg.ch

### What happened?

![image](https://github.com/srozemuller/IntuneAssistant/assets/12907731/3fdc97b7-24aa-45ae-8727-c4a572320bb3)
when select the: Global Assignments Overview and then want to filter for Entra ID Group there is no operator to select and also no possibility to add the value (full name of the group)

### Version

1.0.9

### What OS are you seeing the problem on?

Windows

### Steps to reproduce?

This is what i did. Global Assignments Overview and then want to filter for Entra ID Group there is no operator to select and also no possibility to add the value (full name of the group)

**Comment by srozemuller** [comment]
Issue fixed and updated the web interface

<img width="2684" alt="image" src="https://github.com/srozemuller/IntuneAssistant/assets/43162899/2f6738d3-6d8c-4d3e-91e4-dbf6a93a200c">
