### ISSUE TITLE
Error when exporting to CSV

### ISSUE THREAD

**Issue by bgeijtenbeek** [srozemuller/IntuneAssistant#19]
When I use the --export-csv parameter it gives me an error with regard to filename not being correct.

Whatever file/path I use, it always appends the filename with the datetime and that contains colons. Colons are a no go and so it seems the error comes from that.

I tried everything:
intuneCLI show assignments groups --export-csv filename
intuneCLI show assignments groups --export-csv filename.csv
intuneCLI show assignments groups --export-csv C:\Temp\filename.csv
intuneCLI show assignments groups --export-csv C:\Temp\

It always tries to create (filename.csv)yyyy-mm-ddh:mm:ss.csv
![WhatsApp Image 2023-11-29 at 12 12 48_27ada4a6](https://github.com/srozemuller/IntuneAssistant/assets/91257517/93bb9608-2818-4a9f-8a1b-7af6dd0721da)

**Comment by srozemuller** [comment]
Hi @bgeijtenbeek again thank you for using my tool.
I've managed to fix the issue (I think). On my Mac it is (and was) working fine. I guess the issue had something to do with the :: notation in the filename. 
I also fixed some other bugs regarding the export to CSV. 
Hope it works now. 

The package is updated in the NuGet gallery to version 1.0.4
https://www.nuget.org/packages/IntuneCLI/1.0.4

**Comment by bgeijtenbeek** [comment]
Jup, tested and verified, works great now. Thumbs up for getting getting back to me so quickly!
