### ISSUE TITLE
Cannot seem to run the MacOS Binary

### ISSUE THREAD

**Issue by bwya77** [srozemuller/IntuneAssistant#5]
I am able to run the Windows binary and login but when I dot source (./IntuneAssistant.Cli) in MacOS Terminal or even PowerShell on Mac it doesn't work. 

Terminal says "zsh: permission denied"

When I run with sudo it says "sudo: ./IntuneAssistant.Cli: command not found 

PowerShell returns
No application knows how to open URL file:///Users/bradleywyatt/Dev/IntuneAssistant.Cli (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1608, _LSFunction=runEvaluator}).

I have also tried running the intunecli-osx-arm64-v1 but not sure what runs it as there is no extension. Dot sourcing doesn't work either. 

I am running this on a MacBook Pro, 16in 2021, Apple M1 Pro.

**Comment by coreykeeling** [comment]
You have to make the script executable. I imagine you will need to use the arm64 version as you are on an M1 Mac so change the filename accordingly.

`chmod +x IntuneAssistant.Cli`

Mac will then moan that it's not trusted so you have to go to Settings > Privacy & Security, scroll down to the Security section and there will be an option to allow IntuneAssistant. You need to run it once first in terminal.
 
`./IntuneAssistant.Cli auth login`

It also requires NET to run but it will tell you what you need todo when you run the script.

**Comment by srozemuller** [comment]
The auth login command can be used.  If you run other commands before authentication, a browser will appear to login. 

Yes you need to install dotnet. Check for more information the Microsoft Learn https://learn.microsoft.com/en-us/dotnet/core/install/macos

**Comment by bwya77** [comment]
The auth login wouldnt work until I did what @coreykeeling suggested. It would just say permission denied. 

Once I made it executable it worked no issues 

Thanks, I will close this for now since my issue has been resolved
